#!/usr/bin/env bash

set -e

if [[ -z "${GITHUB_CODESPACE_TOKEN}" ]]; then
  CONFIG="config/install.conf.yaml"
else
  CONFIG="config/install_codespaces.conf.yaml"
fi
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
  --verbose \
  --plugin-dir dotbot-brew \
  -c "${CONFIG}" "${@}"
