#!/bin/bash

#  NOTE(koekeishiya): A list of all built-in modifier and literal keywords can
#                     be found at https://github.com/koekeishiya/skhd/issues/1
#
#                     A hotkey is written according to the following rules:
#
#                       hotkey       = <mode> '<' <action> | <action>
#
#                       mode         = 'name of mode' | <mode> ',' <mode>
#
#                       action       = <keysym> '[' <proc_map_lst> ']' | <keysym> '->' '[' <proc_map_lst> ']'
#                                      <keysym> ':' <command>          | <keysym> '->' ':' <command>
#                                      <keysym> ';' <mode>             | <keysym> '->' ';' <mode>
#
#                       keysym       = <mod> '-' <key> | <key>
#
#                       mod          = 'modifier keyword' | <mod> '+' <mod>
#
#                       key          = <literal> | <keycode>
#
#                       literal      = 'single letter or built-in keyword'
#
#                       keycode      = 'apple keyboard kVK_<Key> values (0x3C)'
#
#                       proc_map_lst = * <proc_map>
#
#                       proc_map     = <string> ':' <command>
#
#                       string       = '"' 'sequence of characters' '"'
#
#                       command      = command is executed through '$SHELL -c' and
#                                      follows valid shell syntax. if the $SHELL environment
#                                      variable is not set, it will default to '/bin/bash'.
#                                      when bash is used, the ';' delimeter can be specified
#                                      to chain commands.
#
#                                      to allow a command to extend into multiple lines,
#                                      prepend '\' at the end of the previous line.
#
#                                      an EOL character signifies the end of the bind.
#
#                       ->           = keypress is not consumed by skhd
#
#  NOTE(koekeishiya): A mode is declared according to the following rules:
#
#                       mode_decl = '::' <name> '@' ':' <command> | '::' <name> ':' <command> |
#                                   '::' <name> '@'               | '::' <name>
#
#                       name      = desired name for this mode,
#
#                       @         = capture keypresses regardless of being bound to an action
#
#                       command   = command is executed through '$SHELL -c' and
#                                   follows valid shell syntax. if the $SHELL environment
#                                   variable is not set, it will default to '/bin/bash'.
#                                   when bash is used, the ';' delimeter can be specified
#                                   to chain commands.
#
#                                   to allow a command to extend into multiple lines,
#                                   prepend '\' at the end of the previous line.
#
#                                   an EOL character signifies the end of the bind.

# add an on_enter command to the default mode
# :: default : chunkc border::color 0xff775759
#
# defines a new mode 'test' with an on_enter command, that captures keypresses
# :: test @ : chunkc border::color 0xff24ccaa
#
# from 'default' mode, activate mode 'test'
# cmd - x ; test
#
# from 'test' mode, activate mode 'default'
# test < cmd - x ; default
#
# launch a new terminal instance when in either 'default' or 'test' mode
# default, test < cmd - return : open -na /Applications/Terminal.app

# application specific bindings
#
# cmd - n [
#     "kitty"       : echo "hello kitty"
#     "qutebrowser" : echo "hello qutebrowser"
#     "finder"      : false
# ]

# narze's config
# Legends
# Leader : Alt
# Navigation : H / J / K / L (vim)
# Prew / Next : < / >
# Move : Leader + Shift
# Resize : Leader + Cmd
# Monitor : I / O
# Desktop : U / P or Leader + Ctrl

# Keycodes
# 0x23 = Colemak semicolon / Qwerty P
# 0x2B = Comma / <
# 0x2F = Fullstop / >

# close focused window
alt - w : osascript -e 'tell application "System Events" to perform action "AXPress" of (first button whose subrole is "AXCloseButton") of (first window whose subrole is "AXStandardWindow") of (first process whose frontmost is true)'

# focus window
alt - h : yabai -m window --focus west
alt - n : yabai -m window --focus south
alt - e : yabai -m window --focus north
alt - i : yabai -m window --focus east

# focus prev/next window, works with floats
alt - 0x2B : echo "$(chunkc tiling::query --desktop windows | sort)""\n" \
             "$(chunkc tiling::query --desktop windows | sort | head -n 1)" | \
             grep -B1 $(chunkc tiling::query --window id) | \
             tail -n2 | head -n1 | sed 's/,.*//' | \
             xargs yabai -m window --focus

alt - 0x2F : echo "$(chunkc tiling::query --desktop windows | sort)""\n" \
             "$(chunkc tiling::query --desktop windows | sort | head -n 1)" | \
             grep -A1 $(chunkc tiling::query --window id) | \
             head -n2 | tail -n1 | sed 's/,.*//' | \
             xargs yabai -m window --focus

# focus monitor
alt - u  : yabai -m display -f prev
alt + ctrl - h  : yabai -m display -f prev
alt - y : yabai -m display -f next # ;
alt + ctrl - i  : yabai -m display -f next

# equalize size of windows
shift + alt - 0 : yabai -m space --equalize

# move window
alt + cmd + shift - h : yabai -m window --warp west
alt + cmd + shift - n : yabai -m window --warp south
alt + cmd + shift - e : yabai -m window --warp north
alt + cmd + shift - i : yabai -m window --warp east

# swap window
alt + shift - h : yabai -m window --swap west
alt + shift - n : yabai -m window --swap south
alt + shift - e : yabai -m window --swap north
alt + shift - i : yabai -m window --swap east

# make floating window fill screen
ctrl + alt + cmd - t : yabai -m window --grid 1:1:0:0:1:1

# float fill left half
ctrl + alt + cmd - h : yabai -m window --grid 1:2:0:0:1:1

# float fill right half
ctrl + alt + cmd - i : yabai -m window --grid 1:2:1:0:1:1

# float fill bottom half
ctrl + alt + cmd - n : yabai -m window --grid 2:1:0:1:1:1

# float fill top half
ctrl + alt + cmd - e : yabai -m window --grid 2:1:0:0:1:1

# create desktop, move window and follow focus
ctrl + alt + cmd - k : yabai -m space --create; \
                       yabai -m window --space last;\
                       yabai -m space --focus last;\
                       yabai -m window --grid 1:1:0:0:1:1

# create desktop and follow focus
# cmd + alt - n : yabai -m space --create;\
#                id=$(chunkc tiling::query --desktops-for-monitor $(chunkc tiling::query --monitor-for-desktop $(chunkc tiling::query --desktop id)));\
#                yabai -m space --focus $(echo ${id##* })

# destroy desktop
ctrl + cmd + alt - w : yabai -m space --destroy

# fast focus desktop
alt + ctrl - 0x2B : yabai -m space --focus recent
alt - l : yabai -m space --focus prev
alt + ctrl - h : yabai -m space --focus prev
alt - 0x23 : yabai -m space --focus next
alt + ctrl - i : yabai -m space --focus next
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8

# send window to desktop
alt + ctrl + shift - 0x2B : yabai -m window --space recent
alt + shift - l : yabai -m window --space prev
alt + ctrl + shift - h  : yabai -m window --space prev
alt + shift - 0x23 : yabai -m window --space next
alt + ctrl + shift - i  : yabai -m window --space next
shift + alt - 1 : yabai -m window --space 1
shift + alt - 2 : yabai -m window --space 2
shift + alt - 3 : yabai -m window --space 3
shift + alt - 4 : yabai -m window --space 4
shift + alt - 5 : yabai -m window --space 5
shift + alt - 6 : yabai -m window --space 6
shift + alt - 7 : yabai -m window --space 7
shift + alt - 8 : yabai -m window --space 8
shift + alt + cmd - 1 : yabai -m window --space 1; yabai -m space -f 1
shift + alt + cmd - 2 : yabai -m window --space 2; yabai -m space -f 2
shift + alt + cmd - 3 : yabai -m window --space 3; yabai -m space -f 3
shift + alt + cmd - 4 : yabai -m window --space 4; yabai -m space -f 4
shift + alt + cmd - 5 : yabai -m window --space 5; yabai -m space -f 5
shift + alt + cmd - 6 : yabai -m window --space 6; yabai -m space -f 6
shift + alt + cmd - 7 : yabai -m window --space 7; yabai -m space -f 7
shift + alt + cmd - 8 : yabai -m window --space 8; yabai -m space -f 8

# send window to desktop and follow focus
# shift + cmd - x : yabai -m window --space $(chunkc get _last_active_desktop); yabai -m space --focus $(chunkc get _last_active_desktop)
# shift + cmd - z : yabai -m window --space prev; yabai -m space --focus prev
# shift + cmd - c : yabai -m window --space next; yabai -m space --focus next
# shift + cmd - 1 : yabai -m window --space 1; yabai -m space --focus 1
# shift + cmd - 2 : yabai -m window --space 2; yabai -m space --focus 2
# shift + cmd - 3 : yabai -m window --space 3; yabai -m space --focus 3
# shift + cmd - 4 : yabai -m window --space 4; yabai -m space --focus 4
# shift + cmd - 5 : yabai -m window --space 5; yabai -m space --focus 5
# shift + cmd - 6 : yabai -m window --space 6; yabai -m space --focus 6
# shift + cmd - 7 : yabai -m window --space 7; yabai -m space --focus 7

# ctrl + alt - 1  : yabai -m display -f 1
# ctrl + alt - 2  : yabai -m display -f 2
# ctrl + alt - 3  : yabai -m display -f 3

# send window to monitor and follow focus
alt + shift - u : yabai -m window --send-to-monitor prev; yabai -m display -f prev
alt + shift - y : yabai -m window --send-to-monitor next; yabai -m display -f next
# shift + alt + cmd - 1  : yabai -m window --send-to-monitor 1; yabai -m display -f 1
# shift + alt + cmd - 2  : yabai -m window --send-to-monitor 2; yabai -m display -f 2
# shift + alt + cmd - 3  : yabai -m window --send-to-monitor 3; yabai -m display -f 3

# increase region size
alt + cmd - a : yabai -m window --use-temporary-ratio 0.05 --adjust-window-edge west
alt + cmd - r : yabai -m window --use-temporary-ratio 0.05 --adjust-window-edge south
alt + cmd - w : yabai -m window --use-temporary-ratio 0.05 --adjust-window-edge north
alt + cmd - s : yabai -m window --use-temporary-ratio 0.05 --adjust-window-edge east

# decrease region size
alt + cmd + ctrl - a : yabai -m window --use-temporary-ratio -0.05 --adjust-window-edge west
alt + cmd + ctrl - r : yabai -m window --use-temporary-ratio -0.05 --adjust-window-edge south
alt + cmd + ctrl - w : yabai -m window --use-temporary-ratio -0.05 --adjust-window-edge north
alt + cmd + ctrl - s : yabai -m window --use-temporary-ratio -0.05 --adjust-window-edge east

# set insertion point for focused container
ctrl + alt - f : yabai -m window --use-insertion-point cancel
ctrl + alt - h : yabai -m window --use-insertion-point west
ctrl + alt - n : yabai -m window --use-insertion-point south
ctrl + alt - e : yabai -m window --use-insertion-point north
ctrl + alt - i : yabai -m window --use-insertion-point east

# rotate tree
alt - r : yabai -m space --rotate 90

# mirror tree y-axis
alt + shift - x : yabai -m space --mirror vertical

# mirror tree x-axis
alt - x : yabai -m space --mirror horizontal

# toggle desktop padding
alt - a : yabai -m space --toggle padding

# toggle window fullscreen
alt - f : yabai -m window --toggle fullscreen

# toggle window native fullscreen
shift + alt - f : yabai -m window --toggle native-fullscreen

# toggle window parent zoom
alt - z : yabai -m window --toggle parent

# toggle window split type
alt - c : yabai -m window --toggle split

# toggle window fade
alt - q : yabai -m window --toggle fade

# float / unfloat window and center on screen
alt - t : yabai -m window --toggle float;\
          yabai -m window --grid 4:4:1:1:2:2

# toggle sticky
alt - s : yabai -m window --toggle sticky

# toggle sticky, float and resize to picture-in-picture size
alt - p : yabai -m window --toggle sticky;\
          yabai -m window --grid 5:5:3:0:2:2

# float next window to be tiled
shift + alt - t : chunkc set window_float_next 1

# change layout of desktop

ctrl + alt - a : yabai -m space --layout bsp
# ctrl + alt - r : yabai -m space --layout monocle # Yabai does not have monocle mode
ctrl + alt - s : yabai -m space --layout float

ctrl + alt - l : yabai -m space --deserialize ~/.chunkwm_layout
ctrl + alt + cmd - l : yabai -m space --serialize ~/.chunkwm_layout

# Fix screenshot taking in app mode
cmd + shift - 4 -> : chunkc border::clear
ctrl + cmd + shift - 4 -> : chunkc border::clear

# MPC commands
ctrl + alt + cmd + shift - 0x23 : mpc toggle
ctrl + alt + cmd - 0x2B : mpc prev
ctrl + alt + cmd - 0x2F : mpc next

# Reload yabai
ctrl + alt + cmd - z : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# Wiggle window
ctrl + alt + cmd - x : yabai -m window --resize top_right:-1:-1 && \
                       yabai -m window --resize top_right:1:1 && \
                       yabai -m window --resize bottom_left:-1:-1 && \
                       yabai -m window --resize bottom_left:1:1
