#!/bin/bash

yabai -m rule --add app="^1Password 7" manage=off
yabai -m rule --add app="^Chrome" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^Fantastical" manage=off
yabai -m rule --add app="^Finder" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
# yabai -m rule --add app="^Firefox$" manage=off

# yabai -m signal --add app="^Firefox$" event=window_focused action="~/.yabai_wiggle.sh"

# # Monitor/desktop 2
# if [[ $(seq $(chunkc tiling::query --monitor count) | tail -n 1) == 1 ]]; then
#   chunkc tiling::rule --owner Slack --state tile --desktop 2 &
#   chunkc tiling::rule --owner Spotify --state tile --desktop 2 &
#   chunkc tiling::rule --owner Safari --except "^$" --state tile --desktop 2 &
#   chunkc tiling::rule --owner Firefox --except "^$" --state tile --desktop 2 &
# else
#   chunkc tiling::rule --owner Slack --state tile --monitor 2 &
#   chunkc tiling::rule --owner Spotify --state tile --monitor 2 &
#   chunkc tiling::rule --owner Safari --except "^$" --state tile --monitor 2 &
#   chunkc tiling::rule --owner Firefox --except "^$" --state tile --monitor 2 &
# fi

# chunkc tiling::rule --owner \"Code - Insiders\" --role AXWindow --subrole AXStandardWindow --state tile --monitor 1 --desktop 1 --grid-layout 1:2:0:0:1:1 &
# chunkc tiling::rule --owner "iTerm2" --state tile --role AXWindow --subrole AXStandardWindow --monitor 1 --desktop 1 --grid-layout 1:2:1:0:1:1 &
# chunkc tiling::rule --owner "iTerm2" --state float --role AXWindow --subrole AXSystemDialog &
