#!/bin/bash

# save as some executable file (chmod +x /path/to/this/script)
# then plug into signal using:
#    yabai -m signal --add event=window_created action="/path/to/this/script"

# the window_created signal carries process id and window id as arguments
pid=$1
wid=$2

if yabai -m query --windows --window $wid \
  | jq -re '.subrole == "AXUnknown" and .floating == 0'
then
  yabai -m window $wid --toggle float
fi

