#!/bin/bash

yabai -m query --windows --space | jq -r '.[] | [.id, .app, .floating] | @tsv' |
  while IFS=$'\t' read -r id app floating; do
    [[ "$floating" -eq "0" ]] && yabai -m window "$id" --toggle float
    yabai -m window "$id" --grid 32:32:2:2:28:28
  done
