#!/bin/bash

# chunkc core::unload tiling.so
# chunkc core::load tiling.so

# if [[ $(seq $(chunkc tiling::query --desktops-for-monitor 1) | tail -n 1) == 1 ]]; then
#   chunkc tiling::desktop --create
# fi

# if [[ $(seq $(chunkc tiling::query --desktops-for-monitor 1) | tail -n 1) == 2 ]]; then
#   chunkc tiling::desktop --create
# fi

# # Monitor/desktop 2
# if [[ $(seq $(chunkc tiling::query --monitor count) | tail -n 1) == 1 ]]; then
#   chunkc tiling::rule --owner Slack --state tile --desktop 2 &
#   chunkc tiling::rule --owner Spotify --state tile --desktop 2 &
#   chunkc tiling::rule --owner Safari --except "^$" --state tile --desktop 2 &
#   chunkc tiling::rule --owner Firefox --except "^$" --state tile --desktop 2 &
# else
#   chunkc tiling::rule --owner Slack --state tile --monitor 2 &
#   chunkc tiling::rule --owner Spotify --state tile --monitor 2 &
#   chunkc tiling::rule --owner Safari --except "^$" --state tile --monitor 2 &
#   chunkc tiling::rule --owner Firefox --except "^$" --state tile --monitor 2 &
# fi

# chunkc tiling::rule --owner Emacs --except "^$" --state tile &

# chunkc tiling::rule --owner \"Code - Insiders\" --role AXWindow --subrole AXStandardWindow --state tile --monitor 1 --desktop 1 --grid-layout 1:2:0:0:1:1 &
# chunkc tiling::rule --owner "iTerm2" --state tile --role AXWindow --subrole AXStandardWindow --monitor 1 --desktop 1 --grid-layout 1:2:1:0:1:1 &
# chunkc tiling::rule --owner "iTerm2" --state float --role AXWindow --subrole AXSystemDialog &

# chunkc tiling::rule --owner "Chrome" --state float &
# chunkc tiling::rule --owner "Fantastical" --state float &
# chunkc tiling::rule --owner \"1Password 7\" --state float &
# # chunkc tiling::rule --owner "Finder" --except "^$" --state float &

# chunkc tiling::rule --owner "System Preferences" --state float &
# chunkc tiling::rule --owner "Dash" --state float &
# chunkc tiling::rule --owner "Preview" --state float &
# chunkc tiling::rule --owner "Time Out" --state float &
