#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FiraCode Nerd Font:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip I II III IV V VI VII VIII IX X XI XII XIII
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             first_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off # Crashes catalina to the login screen
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config window_border_radius         0
yabai -m config active_window_border_color   0xccffc56e
yabai -m config normal_window_border_color   0x22505050
yabai -m config insert_window_border_color   0xccd75f5f
yabai -m config window_border_placement      inset
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.8
yabai -m config split_ratio                  0.6
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               16
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   0

# specific space settings
# yabai -m space 1 --layout                    float

# signals
# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=window_created action="~/.yabai_axunknown_float"

# sh ~/.yabai_rules

yabai -m rule --add label="1Password 7" app="^1Password 7$" manage=off
yabai -m rule --add label="Browserosaurus" app="^Browserosaurus$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Alfred Preferences" app="^Alfred Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Boom 3D" app="^Boom 3D$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dash" app="Dash" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Fantastical" app="Fantastical" manage=off
yabai -m rule --add label="Finder Main" app="^Finder$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Firefox" app="Firefox" manage=off
yabai -m rule --add label="Preview" app="Preview" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Time Out" app="Time Out" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off

echo "yabai configuration loaded.."
