monitorBarOverrides = []
monitorDwindleOverrides = []
monitorGapOverrides = []
monitorNiriOverrides = []
monitorOrientationOverrides = []

[appearance]
mode = "dark"

[borders]
enabled = true
width = 3.0

[borders.color]
alpha = 1.0
blue = 0.979300037944676
green = 1.0
red = 0.08458520228437894

[clipboard]
historyEnabled = false
maxItemBytes = 8388608
maxItems = 200
maxTotalBytes = 67108864

[dwindle]
defaultSplitRatio = 1.0
moveToRootStable = true
singleWindowAspectRatio = "1440x1080"
smartSplit = false
splitWidthMultiplier = 1.0
useGlobalGaps = true

[focus]
crossesMonitorAtEdge = false
followsMouse = false
followsWindowToMonitor = true
moveCrossesMonitorAtEdge = false
moveMouseToFocusedWindow = false

[gaps]
size = 16.0

[gaps.outer]
bottom = 0.0
left = 0.0
right = 0.0
top = 16.0

[general]
animationsEnabled = true
defaultLayoutType = "niri"
hotkeysEnabled = true
hyperKeyHoldThresholdMilliseconds = 150
hyperTrigger = "Left Option"
ipcEnabled = true
preventSleepEnabled = true
spacesTrackingEnabled = true
systemHyperTrigger = "None"
updateChecksEnabled = true

[gestures]
fingerCount = 3
invertDirection = true
mouseResizeModifierKey = "option"
scrollEnabled = true
scrollModifierKey = "optionShift"
scrollSensitivity = 5.0
trackpadScrollStyle = "snap"

[mouseWarp]
enabled = true
margin = 1

[niri]
alwaysCenterSingleColumn = false
centerFocusedColumn = "never"
columnWidthPresets = [0.3333333333333333, 0.5, 0.6666666666666666]
infiniteLoop = true
maxVisibleColumns = 2
singleWindowAspectRatio = "fill"

[quakeTerminal]
animationDuration = 0.2
autoHide = false
enabled = true
heightPercent = 50.0
monitorMode = "focusedWindow"
opacity = 1.0
position = "center"
widthPercent = 50.0

[routing]
mode = "macOS"

[statusBar]
showAppNames = true
showWorkspaceName = true
useWorkspaceId = true

[workspaceBar]
backgroundOpacity = 0.1
deduplicateAppIcons = false
enabled = true
height = 24.0
hideEmptyWorkspaces = false
labelFontSize = 12.0
notchAware = true
position = "overlappingMenuBar"
reserveLayoutSpace = false
showFloatingWindows = true
showLabels = true
windowLevel = "popup"
xOffset = 0.0
yOffset = 0.0

[[appRules]]
bundleId = "com.openai.codex"
id = "6A31F08A-4051-4354-B439-42F4C71894A3"
minHeight = 600.0
minWidth = 800.0

[[appRules]]
bundleId = "com.eltima.cmd1.pro.mas"
id = "4BA546DA-2875-4BEF-B13F-1539E833B1A0"
minHeight = 550.0
minWidth = 950.0

[[appRules]]
bundleId = "com.google.Chrome"
id = "486CEFA6-69AA-4A3C-AF27-BCD38F4F138B"
minHeight = 375.0
minWidth = 500.0

[[appRules]]
bundleId = "dev.zed.Zed"
id = "979F05F4-FFA2-4EDD-B23F-08A9944C759F"
minHeight = 240.0
minWidth = 360.0

[[appRules]]
bundleId = "com.apple.Safari"
id = "81426D13-C1A5-475E-AFBC-00BBA05042D0"
minHeight = 220.0
minWidth = 574.0

[[appRules]]
bundleId = "app.zen-browser.zen"
id = "1CF39647-F30D-4E76-9686-79B551F1B094"
minHeight = 495.0
minWidth = 500.0

[[appRules]]
bundleId = "org.mozilla.firefox"
id = "005C00D3-F665-47F8-BDAE-D80790E9E46B"
minHeight = 120.0
minWidth = 500.0

[[appRules]]
bundleId = "company.thebrowser.dia"
id = "C21156B1-0224-4998-97E3-8F4FA65B9F3B"
minHeight = 420.0
minWidth = 500.0

[[appRules]]
bundleId = "com.spotify.client"
id = "2DE9390B-0DB4-4D0C-9ABA-06F76F1D4EA9"
minHeight = 600.0
minWidth = 800.0

[[appRules]]
bundleId = "com.hnc.Discord"
id = "AF752D95-8497-4844-BE20-4C93E73BAEF2"
minHeight = 500.0
minWidth = 800.0

[[appRules]]
bundleId = "com.mitchellh.ghostty"
id = "7876C9EF-437E-4D4F-9C27-B1B02F4AABCE"
minHeight = 48.0
minWidth = 90.0

[[appRules]]
bundleId = "com.microsoft.Outlook"
id = "8ECAB78B-BCDD-4245-BC25-1609A49B1C86"
minHeight = 650.0
minWidth = 930.0

[[appRules]]
bundleId = "com.apple.MobileSMS"
id = "552FB77D-BF0E-4737-90A6-B5BC6986C579"
minHeight = 320.0
minWidth = 660.0

[[hotkeys]]
binding = "Option+1"
id = "switchWorkspace.0"

[[hotkeys]]
binding = "Option+Shift+1"
id = "moveToWorkspace.0"

[[hotkeys]]
binding = "Option+2"
id = "switchWorkspace.1"

[[hotkeys]]
binding = "Option+Shift+2"
id = "moveToWorkspace.1"

[[hotkeys]]
binding = "Option+3"
id = "switchWorkspace.2"

[[hotkeys]]
binding = "Option+Shift+3"
id = "moveToWorkspace.2"

[[hotkeys]]
binding = "Option+4"
id = "switchWorkspace.3"

[[hotkeys]]
binding = "Option+Shift+4"
id = "moveToWorkspace.3"

[[hotkeys]]
binding = "Option+5"
id = "switchWorkspace.4"

[[hotkeys]]
binding = "Option+Shift+5"
id = "moveToWorkspace.4"

[[hotkeys]]
binding = "Option+6"
id = "switchWorkspace.5"

[[hotkeys]]
binding = "Option+Shift+6"
id = "moveToWorkspace.5"

[[hotkeys]]
binding = "Option+7"
id = "switchWorkspace.6"

[[hotkeys]]
binding = "Option+Shift+7"
id = "moveToWorkspace.6"

[[hotkeys]]
binding = "Option+8"
id = "switchWorkspace.7"

[[hotkeys]]
binding = "Option+Shift+8"
id = "moveToWorkspace.7"

[[hotkeys]]
binding = "Option+9"
id = "switchWorkspace.8"

[[hotkeys]]
binding = "Option+Shift+9"
id = "moveToWorkspace.8"

[[hotkeys]]
binding = "Unassigned"
id = "workspaceBackAndForth"

[[hotkeys]]
binding = "Option+P"
id = "switchWorkspace.next"

[[hotkeys]]
binding = "Option+U"
id = "switchWorkspace.previous"

[[hotkeys]]
binding = "Option+H"
id = "focus.left"

[[hotkeys]]
binding = "Option+J"
id = "focus.down"

[[hotkeys]]
binding = "Option+K"
id = "focus.up"

[[hotkeys]]
binding = "Option+L"
id = "focus.right"

[[hotkeys]]
binding = "Option+Quote"
id = "focusPrevious"

[[hotkeys]]
binding = "Unassigned"
id = "focusDownOrLeft"

[[hotkeys]]
binding = "Unassigned"
id = "focusUpOrRight"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowTop"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowBottom"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowDownOrTop"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowUpOrBottom"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowOrWorkspaceDown"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowOrWorkspaceUp"

[[hotkeys]]
binding = "Hyper+C"
id = "centerColumn"

[[hotkeys]]
binding = "Unassigned"
id = "centerVisibleColumns"

[[hotkeys]]
binding = "Unassigned"
id = "moveWindowToWorkspaceUp"

[[hotkeys]]
binding = "Unassigned"
id = "moveWindowToWorkspaceDown"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspaceUp"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspaceDown"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.0"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.1"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.2"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.3"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.4"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.5"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.6"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.7"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.8"

[[hotkeys]]
binding = "Option+Shift+H"
id = "move.left"

[[hotkeys]]
binding = "Option+Shift+J"
id = "move.down"

[[hotkeys]]
binding = "Option+Shift+K"
id = "move.up"

[[hotkeys]]
binding = "Option+Shift+L"
id = "move.right"

[[hotkeys]]
binding = "Unassigned"
id = "moveWindowDown"

[[hotkeys]]
binding = "Unassigned"
id = "moveWindowUp"

[[hotkeys]]
binding = "Unassigned"
id = "moveWindowDownOrToWorkspaceDown"

[[hotkeys]]
binding = "Unassigned"
id = "moveWindowUpOrToWorkspaceUp"

[[hotkeys]]
binding = "Unassigned"
id = "consumeOrExpelWindowLeft"

[[hotkeys]]
binding = "Unassigned"
id = "consumeOrExpelWindowRight"

[[hotkeys]]
binding = "Unassigned"
id = "consumeWindowIntoColumn"

[[hotkeys]]
binding = "Unassigned"
id = "expelWindowFromColumn"

[[hotkeys]]
binding = "Option+O"
id = "focusMonitorNext"

[[hotkeys]]
binding = "Option+I"
id = "focusMonitorPrevious"

[[hotkeys]]
binding = "Control+Command+Grave"
id = "focusMonitorLast"

[[hotkeys]]
binding = "Option+Return"
id = "toggleFullscreen"

[[hotkeys]]
binding = "Option+Shift+Return"
id = "toggleNativeFullscreen"

[[hotkeys]]
binding = "Hyper+H"
id = "moveColumn.left"

[[hotkeys]]
binding = "Hyper+L"
id = "moveColumn.right"

[[hotkeys]]
binding = "Hyper+Home"
id = "moveColumnToFirst"

[[hotkeys]]
binding = "Hyper+End"
id = "moveColumnToLast"

[[hotkeys]]
binding = "Hyper+T"
id = "toggleColumnTabbed"

[[hotkeys]]
binding = "Option+Home"
id = "focusColumnFirst"

[[hotkeys]]
binding = "Option+End"
id = "focusColumnLast"

[[hotkeys]]
binding = "Hyper+1"
id = "focusColumn.0"

[[hotkeys]]
binding = "Hyper+2"
id = "focusColumn.1"

[[hotkeys]]
binding = "Hyper+3"
id = "focusColumn.2"

[[hotkeys]]
binding = "Hyper+4"
id = "focusColumn.3"

[[hotkeys]]
binding = "Hyper+5"
id = "focusColumn.4"

[[hotkeys]]
binding = "Hyper+6"
id = "focusColumn.5"

[[hotkeys]]
binding = "Hyper+7"
id = "focusColumn.6"

[[hotkeys]]
binding = "Hyper+8"
id = "focusColumn.7"

[[hotkeys]]
binding = "Hyper+9"
id = "focusColumn.8"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowInColumn.1"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowInColumn.2"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowInColumn.3"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowInColumn.4"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowInColumn.5"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowInColumn.6"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowInColumn.7"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowInColumn.8"

[[hotkeys]]
binding = "Unassigned"
id = "focusWindowInColumn.9"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToIndex.1"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToIndex.2"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToIndex.3"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToIndex.4"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToIndex.5"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToIndex.6"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToIndex.7"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToIndex.8"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToIndex.9"

[[hotkeys]]
binding = "Hyper+Period"
id = "cycleColumnWidthForward"

[[hotkeys]]
binding = "Hyper+Comma"
id = "cycleColumnWidthBackward"

[[hotkeys]]
binding = "Unassigned"
id = "cycleWindowWidthForward"

[[hotkeys]]
binding = "Unassigned"
id = "cycleWindowWidthBackward"

[[hotkeys]]
binding = "Unassigned"
id = "cycleWindowHeightForward"

[[hotkeys]]
binding = "Unassigned"
id = "cycleWindowHeightBackward"

[[hotkeys]]
binding = "Option+Shift+F"
id = "toggleColumnFullWidth"

[[hotkeys]]
binding = "Hyper+F"
id = "expandColumnToAvailableWidth"

[[hotkeys]]
binding = "Hyper+R"
id = "resetWindowHeight"

[[hotkeys]]
binding = "Option+Minus"
id = "setColumnWidth.decrease10Percent"

[[hotkeys]]
binding = "Option+Equal"
id = "setColumnWidth.increase10Percent"

[[hotkeys]]
binding = "Unassigned"
id = "setWindowWidth.decrease10Percent"

[[hotkeys]]
binding = "Unassigned"
id = "setWindowWidth.increase10Percent"

[[hotkeys]]
binding = "Hyper+Minus"
id = "setWindowHeight.decrease10Percent"

[[hotkeys]]
binding = "Hyper+Equal"
id = "setWindowHeight.increase10Percent"

[[hotkeys]]
binding = "Hyper+B"
id = "balanceSizes"

[[hotkeys]]
binding = "Unassigned"
id = "moveToRoot"

[[hotkeys]]
binding = "Unassigned"
id = "toggleSplit"

[[hotkeys]]
binding = "Unassigned"
id = "swapSplit"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.left"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.right"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.up"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.down"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.left"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.right"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.up"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.down"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.left"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.right"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.up"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.down"

[[hotkeys]]
binding = "Unassigned"
id = "preselectClear"

[[hotkeys]]
binding = "Control+Option+Space"
id = "openCommandPalette"

[[hotkeys]]
binding = "Option+Shift+R"
id = "raiseAllFloatingWindows"

[[hotkeys]]
binding = "Unassigned"
id = "rescueOffscreenWindows"

[[hotkeys]]
binding = "Option+F"
id = "toggleFocusedWindowFloating"

[[hotkeys]]
binding = "Hyper+E"
id = "assignFocusedWindowToScratchpad"

[[hotkeys]]
binding = "Option+Shift+E"
id = "toggleScratchpadWindow"

[[hotkeys]]
binding = "Control+Option+M"
id = "openMenuAnywhere"

[[hotkeys]]
binding = "Unassigned"
id = "toggleWorkspaceBarVisibility"

[[hotkeys]]
binding = "Unassigned"
id = "toggleHiddenBar"

[[hotkeys]]
binding = "Option+Grave"
id = "toggleQuakeTerminal"

[[hotkeys]]
binding = "Option+R"
id = "toggleWorkspaceLayout"

[[hotkeys]]
binding = "Option+Shift+O"
id = "toggleOverview"

[[monitorRoutingOverrides]]
gridColumn = 0
gridRow = 0
monitorDisplayId = 1
monitorName = "Built-in Retina Display"

[[workspaces]]
id = "AD36F001-C57E-41A5-AC1D-DF5249D007F0"
layoutType = "niri"
name = "1"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "454CECD4-5E9D-4ED1-95D7-979D48817F5F"
layoutType = "niri"
name = "2"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
displayName = "❤️"
id = "5953F2BF-A378-4266-91B2-287174C4FA4D"
layoutType = "niri"
name = "6"

[workspaces.monitorAssignment]
type = "secondary"

[[workspaces]]
displayName = "🚀"
id = "A7D5E104-6985-4516-8ED5-07F144F2A33D"
layoutType = "niri"
name = "7"

[workspaces.monitorAssignment]
type = "secondary"

[[workspaces]]
id = "25BD47A0-48CA-47E4-AEF9-316BD6AE028E"
layoutType = "niri"
name = "8"

[workspaces.monitorAssignment]
type = "specificDisplay"

[workspaces.monitorAssignment.output]
displayId = 1
name = "Built-in Retina Display"
