#!/usr/bin/env zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export EDITOR=nvim
export TERM=xterm-256color
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export PATH="/usr/local/sbin:$HOME/.dotfiles/etc/bin:$PATH"
export PATH="/Applications/Postgres.app/Contents/Versions/9.6/bin:$PATH"

# force zsh-you-should-use
export YSU_HARDCORE=1

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

ulimit -n 8192

# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs rbenv rspec_stats newline)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator ip background_jobs history time)

# Prefer using emacs mode for zsh
bindkey -e

source ~/.zinit/bin/zinit.zsh

# Turbo mode with "wait"
zinit light-mode lucid wait for \
  is-snippet OMZ::lib/history.zsh \
  MichaelAquilina/zsh-you-should-use \
  romkatv/zsh-prompt-benchmark \
  zdharma/history-search-multi-word \
  zinit-zsh/z-a-bin-gem-node \
  atload"unalias zi; alias zi='zinit'" \
    ajeetdsouza/zoxide

zinit ice wait"1" atload'_history_substring_search_bind_keys' lucid
zinit light zsh-users/zsh-history-substring-search

# Ref: zdharma/fast-syntax-highlighting
# Note: Use wait 1 second works for kubectl
zinit wait lucid for \
  atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma/fast-syntax-highlighting \
  atload"zpcdreplay" wait"1" \
    OMZP::kubectl \
  blockf \
    zsh-users/zsh-completions \
  atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions \
  as"completion" is-snippet \
    https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker \
    https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose

zinit pack"bgn-binary" for fzf
zinit pack"bgn" for fzy

zinit ice atload'!source ~/.p10k.zsh' lucid nocd
zinit light romkatv/powerlevel10k

# Load my zsh dotfiles, aliases
zinit light-mode is-snippet lucid for \
  $HOME/.dotfiles/zsh/config/00_aliases.zsh \
  $HOME/.dotfiles/zsh/config/10_options.zsh \
  $HOME/.dotfiles/zsh/config/20_functions.zsh

# Compinit : After zinits, before cdreplay
# https://carlosbecker.com/posts/speeding-up-zsh/
autoload -Uz compinit
if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]; then
  compinit;
else
  compinit -C;
fi

zinit cdreplay -q

# Kitty autocompletion (Place after compinit)
kitty + complete setup zsh | source /dev/stdin

# Key bindings for zsh-history-substring-search
_history_substring_search_bind_keys() {
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down
  bindkey -M emacs '^P' history-substring-search-up
  bindkey -M emacs '^N' history-substring-search-down
  bindkey -M vicmd 'k' history-substring-search-up
  bindkey -M vicmd 'j' history-substring-search-down
}

if [ -d "$HOME/.asdf" ]; then
  . $HOME/.asdf/asdf.sh
fi

if [ -d "$HOME/.asdf/plugins/java" ]; then
  zinit ice wait"0" pick".asdf/plugins/java/set-java-home.sh" lucid
  zinit light %HOME
fi

if [ -d "$HOME/.rbenv" ]; then
  eval "$(rbenv init - --no-rehash)"
fi

if [ -d "$HOME/.jenv" ]; then
  export PATH="$HOME/.jenv/bin:$PATH"
  eval "$(jenv init -)"
fi

# Timing App Terminal Support
if [ $ITERM_SESSION_ID ]; then
  DISABLE_AUTO_TITLE="true"
  echo -ne "\033]0; @ ${HOST%%.*} : ${PWD/#$HOME/~} \007"
fi

precmd() {
  echo -ne "\033]0; @ ${HOST%%.*} : ${PWD/#$HOME/~} \007"
}

if [ -f "$HOME/.zshrc.local" ]; then
  source "$HOME/.zshrc.local"
fi

# source ~/.bashhub/bashhub.zsh
if [ -f ~/.bashhub/bashhub.zsh ]; then
  zinit ice wait"0" pick".bashhub/bashhub.zsh" lucid
  zinit light %HOME
fi

# Override zinit m() function
# Ref: https://github.com/zdharma/zinit/commit/7ed6ab9dc535a079275a721bf3e7b4713900430c
m() {
  git commit -m "$*"
}
