#!/usr/bin/env bash

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

# This is a demo config to bring across some of the most important commands more easily.
# For a more advanced configuration example see https://github.com/FelixKratz/SketchyBar/discussions/47#discussion-3587958
############## BAR ##############
if [ "$(sysctl -n machdep.cpu.brand_string)" = "Apple M1 Pro" ]; then
  BAR_HEIGHT=42
  LEFT_NOTCH_POSITION=q
  RIGHT_NOTCH_POSITION=e
else
  BAR_HEIGHT=36
  LEFT_NOTCH_POSITION=center
  RIGHT_NOTCH_POSITION=right
fi

TRANSPARENT=0x00000000
# BG=0xfa232639
BG=0xf0c0caf5
FONT_FACE="MonaspiceKr Nerd Font"

# Custom event
sketchybar --add event window_change

sketchybar -m --bar height=$BAR_HEIGHT \
                    blur_radius=50   \
                    position=top     \
                    padding_left=10  \
                    padding_top=10  \
                    padding_right=10 \
                    color=$TRANSPARENT \
                    y_offset=0

############## GLOBAL DEFAULTS ##############
sketchybar -m --default icon.font="$FONT_FACE:Regular:17.0"  \
                        icon.color=$BG                 \
                        label.font="$FONT_FACE:Bold:12.0" \
                        label.color=$BG \
                        background.color=$TRANSPARENT \
                        background.border_color=$BG \
                        background.border_width=2 \
                        background.corner_radius=6 \
                        background.padding_right=5 \
                        background.height=26

############## SPACE DEFAULTS ##############
sketchybar -m --default label.padding_left=2  \
                        label.padding_right=2 \
                        icon.padding_left=8   \
                        label.padding_right=8

###################### AeroSpace Spaces ###################
sketchybar --add alias "AeroSpace,Item-0" $LEFT_NOTCH_POSITION \
           --set "AeroSpace,Item-0" alias.color=$BG \
                                  icon.padding_left=0   \
                                  icon.padding_right=0  \
                                  label.padding_left=0  \
                                  label.padding_right=0 \
           --subscribe "AeroSpace,Item-0" aerospace_workspace_change

sketchybar --add event aerospace_workspace_change

# NOTE: AeroSpace & Sketchybar have different monitor IDs so we can't add icons according to the display yet
# for mid in $(aerospace list-monitors | awk -F " | " '{print $1}'); do
for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item aerospace.$sid left \
    --subscribe aerospace.$sid aerospace_workspace_change \
    --set aerospace.$sid \
    background.color=0x44ffffff \
    background.drawing=off \
    background.border_color=$BG \
    background.border_width=2 \
    label="$sid" \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# https://github.com/FelixKratz/SketchyBar/discussions/12?sort=top#discussioncomment-6974258
COLOR_BACKGROUND=0xe01d2021
COLOR_FOREGROUND=0xe0fbf1c7
COLOR_BLACK=0xe0282828
COLOR_RED=0xe0cc241d
COLOR_GREEN=0xe098971a
COLOR_YELLOW=0xe0d79921
COLOR_BLUE=0xe0458588
COLOR_MAGENTA=0xe0b16286
COLOR_CYAN=0xe0689d6a
COLOR_WHITE=0xe0a89984
ICONS_SPACE=(󰎤 󰎧 󰎪 󰎭 󰎱 󰎳 󰎶)
COLORS_SPACE=($COLOR_YELLOW $COLOR_CYAN $COLOR_MAGENTA $COLOR_WHITE $COLOR_BLUE $COLOR_RED $COLOR_GREEN)
LENGTH=${#ICONS_SPACE[@]}

# Yabai Spaces
# for i in "${!ICONS_SPACE[@]}"
# do
#   sid=$(($i+1))
#   PAD_LEFT=2
#   PAD_RIGHT=2
#   if [[ $i == 0 ]]; then
#     PAD_LEFT=8
#   elif [[ $i == $(($LENGTH-1)) ]]; then
#     PAD_RIGHT=8
#   fi
#   sketchybar --add space space.$sid left                                       \
#              --set       space.$sid script="$PLUGIN_DIR/app_space.sh"          \
#                                     associated_space=$sid                      \
#                                     padding_left=$PAD_LEFT                     \
#                                     padding_right=$PAD_RIGHT                   \
#                                     background.color=${COLORS_SPACE[i]}        \
#                                     background.border_width=0                  \
#                                     background.corner_radius=6                 \
#                                     background.height=24                       \
#                                     icon=${ICONS_SPACE[i]}                     \
#                                     icon.color=${COLORS_SPACE[i]}              \
#                                     label="_"                                  \
#                                     label.color=${COLORS_SPACE[i]}             \
#              --subscribe space.$sid front_app_switched window_change
# done

# # Space bracket
# sketchybar --add bracket spaces '/space\..*/'                      \
#            --set         spaces background.color=$COLOR_BACKGROUND

# ############## PRIMARY DISPLAY SPACES ##############
# sketchybar -m --add space term left                              \
#               --set term associated_display=1                    \
#                          associated_space=1                      \
#                          icon.font="FantasqueSansM Nerd Font:Bold:20.0"    \
#                          icon=                                  \
#                          icon.highlight_color=0xfffab402         \
#                          label=Term                              \
#                          click_script="yabai -m space --focus 1" \
#                                                                  \
#               --add space editor left                               \
#               --set editor associated_display=1                    \
#                          associated_space=2                      \
#                          icon=󰈮                                  \
#                          icon.highlight_color=0xfffab402         \
#                          label=Editor                               \
#                          click_script="yabai -m space --focus 2" \
#                                                                  \
#               --add space browse left                               \
#               --set browse associated_display=1                    \
#                          associated_space=3                      \
#                          icon=                                  \
#                          icon.highlight_color=0xfffab402         \
#                          label=Browse                               \
#                          click_script="yabai -m space --focus 3" \
#                                                                  \
#               --add space misc left                               \
#               --set misc associated_display=1                    \
#                          associated_space=4                      \
#                          icon=                                  \
#                          icon.highlight_color=0xfffab402         \
#                          label=Misc                               \
#                          click_script="yabai -m space --focus 4" \
#                                                                  \
#               --add space offscreen left                               \
#               --set offscreen associated_display=1                    \
#                          associated_space=5                      \
#                          icon=󰹑                                  \
#                          icon.highlight_color=0xfffab402         \
#                          click_script="yabai -m space --focus 5"

# ############## SECONDARY DISPLAY SPACES ##############
# sketchybar -m --add space offscreen_2 left                              \
#               --set offscreen_2 associated_display=2                    \
#                          associated_space=5                      \
#                          icon.font="FantasqueSansM Nerd Font:Bold:20.0"    \
#                          icon=󰹑                                  \
#                          icon.highlight_color=0xff48aa2a         \
#                          label=OffScreen                              \
#                          click_script="yabai -m space --focus 5"

############## ITEM DEFAULTS ###############
sketchybar -m --default label.padding_left=2  \
                        icon.padding_right=2  \
                        icon.padding_left=6   \
                        label.padding_right=6


############## LEFT ITEMS ##############
# sketchybar -m --add item space_separator left                                                  \
#               --set space_separator  icon=                                                    \
#                                      associated_space=1                                        \
#                                      icon.padding_left=15                                      \
#                                      label.padding_right=15                                    \
#                                      icon.font="FantasqueSansM Nerd Font:Bold:15.0"                      \
#                                                                                                \
#               --add item gitNotifications left                                                 \
#               --set gitNotifications associated_space=1                                        \
#                                      update_freq=300                                           \
#                                      icon.font="FantasqueSansM Nerd Font:Bold:18.0"            \
#                                      icon=                                                    \
#                                      script="$PLUGIN_DIR/gitNotifications.sh" \
#                                      click_script="open https://github.com/notifications"      \
#               --subscribe gitNotifications system_woke                                         \
#                                                                                                \
#               --add item githubIndicator left                                                  \
#               --set githubIndicator  associated_space=1                                        \
#                                      update_freq=1000                                          \
#                                      icon.font="FantasqueSansM Nerd Font:Bold:18.0"                      \
#                                      icon=                                                    \
#                                      click_script="open https://github.com"                    \
#                                      script="$PLUGIN_DIR/githubIndicator.sh"  \
#               --subscribe githubIndicator system_woke                                          \
#                                                                                                \
#               --add item topmem left                                                           \
#               --set topmem           associated_space=1                                        \
#                                      icon.padding_left=10                                      \
#                                      update_freq=15                                            \
#                                      script="$PLUGIN_DIR/topmem.sh"

sketchybar --add item window_title $LEFT_NOTCH_POSITION               \
           --set window_title    script="$PLUGIN_DIR/window_title.sh" \
                                 label.padding_left=16               \
                                 label.padding_right=16               \
                                 background.padding_right=16            \
                                 icon.drawing=off                     \
                                 drawing=off \
           --subscribe window_title front_app_switched

############## RIGHT ITEMS ##############
sketchybar -m --add item clock right                                                                  \
              --set clock         update_freq=10                                                      \
                                  script="$PLUGIN_DIR/clock.sh"                      \
              #                                                                                         \
              # --add item mailIndicator right                                                          \
              # --set mailIndicator associated_space=1,2,3                                              \
              #                     update_freq=30                                                      \
              #                     script="$PLUGIN_DIR/mailIndicator.sh"              \
              #                     icon.font="FantasqueSansM Nerd Font:Bold:20.0"                                \
              #                     icon=                                                              \
              #                     click_script="osascript -e 'tell application \"Mail\" to activate'"

keyboard=(
    icon.drawing=off
    label.font="$FONT_FACE:Semibold:14.0"
    script="$PLUGIN_DIR/keyboard.sh"
)
sketchybar --add item keyboard right        \
           --set keyboard "${keyboard[@]}"  \
           --add event keyboard_change "AppleSelectedInputSourcesChangedNotification" \
           --subscribe keyboard keyboard_change

sketchybar --add item mic right \
           --set mic script="$PLUGIN_DIR/mic.sh" \
           --set mic click_script="$PLUGIN_DIR/mic_click.sh" \
           --add event mic_vol_change \
           --subscribe mic mic_vol_change

sketchybar --add item wifi right                         \
           --set wifi    script="$PLUGIN_DIR/wifi.sh"    \
                         background.padding_right=12     \
                         update_freq=120 \
           --subscribe wifi wifi_change

sketchybar -m --add item battery right \
              --set battery update_freq=60 \
              --set battery script="$PLUGIN_DIR/power.sh" \
              --subscribe battery power_source_change

sketchybar --add alias "Session,Item-0" right \
           --set "Session,Item-0" alias.color=$BG \
                                  icon.padding_left=0   \
                                  icon.padding_right=0  \
                                  label.padding_left=0  \
                                  label.padding_right=0

# Creating Graphs
sketchybar -m --add graph cpu_user right 64                                         \
              --set cpu_user     graph.color=0xff000000                             \
                                 update_freq=1                                      \
                                 width=0                                            \
                                 label.padding_left=0                               \
                                 icon=                                             \
                                 script="$PLUGIN_DIR/cpu_graph.sh" \
                                 lazy=on                                            \
                                                                                    \
              --add graph cpu_sys right 64                                          \
              --set cpu_sys      label.padding_left=0                               \
                                 icon=                                             \
                                 graph.color=0xff48aa2a                             \
                                                                                    \
              --add item topproc right                                              \
              --set topproc      label.padding_right=10                             \
                                 update_freq=15                                     \
                                 script="$PLUGIN_DIR/topproc.sh"

###################### CENTER ITEMS ################### (Right of the notch)

# Adding custom events which can listen on distributed notifications from other running processes
# sketchybar -m --add event spotify_change "com.spotify.client.PlaybackStateChanged"                       \
#               --add item spotifyIndicator $RIGHT_NOTCH_POSITION                                           \
#               --set spotifyIndicator script="$PLUGIN_DIR/spotifyIndicator.sh"           \
#               --set spotifyIndicator click_script="osascript -e 'tell application \"Spotify\" to pause'" \
#               --set spotifyIndicator background.padding_left=16            \
#               --subscribe spotifyIndicator spotify_change
# sketchybar -m --add item sonixdIndicator $RIGHT_NOTCH_POSITION                                           \
#               --set sonixdIndicator script="ruby $PLUGIN_DIR/sonixdIndicator.rb"           \
#                                     click_script="ruby $PLUGIN_DIR/sonixdIndicator.rb" \
#                                     update_freq=15

############## FINALIZING THE SETUP ##############
sketchybar -m --update

echo "sketchybar configuration loaded.."
